# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_driver.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setSpacing(100)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Measure_Gauge = QtWidgets.QProgressBar(self.centralwidget)
        self.Measure_Gauge.setStyleSheet("QProgressBar {\n"
"border: 2px solid rgba(33, 37, 43, 180);\n"
"border-radius: 5px;\n"
"text-align: center;\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color:transparent;\n"
"color: black;\n"
"width: 80;\n"
"\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.Measure_Gauge.setMaximum(400)
        self.Measure_Gauge.setProperty("value", 0)
        self.Measure_Gauge.setTextVisible(True)
        self.Measure_Gauge.setOrientation(QtCore.Qt.Vertical)
        self.Measure_Gauge.setInvertedAppearance(False)
        self.Measure_Gauge.setObjectName("Measure_Gauge")
        self.horizontalLayout_3.addWidget(self.Measure_Gauge)
        self.Senales = QtWidgets.QVBoxLayout()
        self.Senales.setObjectName("Senales")
        self.horizontalLayout_3.addLayout(self.Senales)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Espacio = QtWidgets.QLabel(self.centralwidget)
        self.Espacio.setText("")
        self.Espacio.setObjectName("Espacio")
        self.horizontalLayout.addWidget(self.Espacio)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.IP_address_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.IP_address_2.setObjectName("IP_address_2")
        self.horizontalLayout_4.addWidget(self.IP_address_2)
        self.Conectar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Conectar_2.setObjectName("Conectar_2")
        self.horizontalLayout_4.addWidget(self.Conectar_2)
        self.Desconectar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Desconectar_2.setEnabled(False)
        self.Desconectar_2.setObjectName("Desconectar_2")
        self.horizontalLayout_4.addWidget(self.Desconectar_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interfaz para prueba con perfil de velocidad"))
        self.Measure_Gauge.setFormat(_translate("MainWindow", "%v km/h"))
        self.label_2.setText(_translate("MainWindow", "Velocidad\n"
"actual"))
        self.label_4.setText(_translate("MainWindow", "Dirección IP del servidor"))
        self.Conectar_2.setText(_translate("MainWindow", "Conectar"))
        self.Desconectar_2.setText(_translate("MainWindow", "Desconectar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
