from simpful import *

def sistema_mamdani():
        FS = FuzzySystem()

        T_1 = FuzzySet(function=Triangular_MF(a=0, b=37, c=94), term="N")
        T_2 = FuzzySet(function=Triangular_MF(a=37, b=94, c=175), term="MB")
        T_3 = FuzzySet(function=Triangular_MF(a=94, b=175, c=270), term="B")
        T_4 = FuzzySet(function=Triangular_MF(a=175, b=270, c=388), term="M")
        T_5 = FuzzySet(function=Triangular_MF(a=270, b=388, c=520), term="A")
        T_6 = FuzzySet(function=Triangular_MF(a=388, b=520, c=520), term="MA")
        LV1 = LinguisticVariable([T_1, T_2, T_3, T_4, T_5, T_6], concept="Torque Medido", universe_of_discourse=[0,500])
        FS.add_linguistic_variable("T", LV1)

        RPM_1 = FuzzySet(function=Triangular_MF(a=0, b=0, c=50), term="N")
        RPM_2 = FuzzySet(function=Triangular_MF(a=0, b=50, c=100), term="B")
        RPM_3 = FuzzySet(function=Trapezoidal_MF(a=80, b=150, c=400, d=550), term="M")
        RPM_4 = FuzzySet(function=Triangular_MF(a=450, b=550, c=550), term="A")
        LV2 = LinguisticVariable([RPM_1, RPM_2, RPM_3, RPM_4], concept="RPM Medido", universe_of_discourse=[0,550])
        FS.add_linguistic_variable("RPM", LV2)

        ET_1 = FuzzySet(function=Triangular_MF(a=-500, b=-500, c=-400), term="NMA")
        ET_2 = FuzzySet(function=Triangular_MF(a=-500, b=-400, c=-300), term="NA")
        ET_3 = FuzzySet(function=Triangular_MF(a=-400, b=-300, c=-200), term="NM")
        ET_4 = FuzzySet(function=Triangular_MF(a=-300, b=-200, c=-100), term="NB")
        ET_5 = FuzzySet(function=Triangular_MF(a=-200, b=-100, c=0), term="NMB")
        ET_6 = FuzzySet(function=Triangular_MF(a=-100, b=-2, c=0), term="NN")
        ET_7 = FuzzySet(function=Triangular_MF(a=0, b=2, c=100), term="PN")
        ET_8 = FuzzySet(function=Triangular_MF(a=0, b=100, c=200), term="PMB")
        ET_9 = FuzzySet(function=Triangular_MF(a=100, b=200, c=300), term="PB")
        ET_10 = FuzzySet(function=Triangular_MF(a=200, b=300, c=400), term="PM")
        ET_11 = FuzzySet(function=Triangular_MF(a=300, b=400, c=500), term="PA")
        ET_12 = FuzzySet(function=Triangular_MF(a=400, b=500, c=500), term="PMA")
        LV3 = LinguisticVariable([ET_1, ET_2, ET_3, ET_4, ET_5, ET_6, ET_7, ET_8, ET_9, ET_10, ET_11, ET_12], concept="Error de Torque", universe_of_discourse=[-500,500])
        FS.add_linguistic_variable("ET", LV3)

        CET_1 = FuzzySet(function=Triangular_MF(a=-100, b=-100, c=-80), term="NMA")
        CET_2 = FuzzySet(function=Triangular_MF(a=-100, b=-80, c=-60), term="NA")
        CET_3 = FuzzySet(function=Triangular_MF(a=-80, b=-60, c=-40), term="NM")
        CET_4 = FuzzySet(function=Triangular_MF(a=-60, b=-40, c=-20), term="NB")
        CET_5 = FuzzySet(function=Triangular_MF(a=-40, b=-20, c=0), term="NMB")
        CET_6 = FuzzySet(function=Triangular_MF(a=-20, b=0, c=20), term="N")
        CET_7 = FuzzySet(function=Triangular_MF(a=0, b=20, c=40), term="PMB")
        CET_8 = FuzzySet(function=Triangular_MF(a=20, b=40, c=60), term="PB")
        CET_9 = FuzzySet(function=Triangular_MF(a=40, b=60, c=80), term="PM")
        CET_10 = FuzzySet(function=Triangular_MF(a=60, b=80, c=100), term="PA")
        CET_11 = FuzzySet(function=Triangular_MF(a=80, b=100, c=100), term="PMA")
        LV4 = LinguisticVariable([CET_1, CET_2, CET_3, CET_4, CET_5, CET_6, CET_7, CET_8, CET_9, CET_10, CET_11], concept="Cambio en Error de Torque", universe_of_discourse=[-100,100])
        FS.add_linguistic_variable("CET", LV4)

        V_1 = FuzzySet(function=Triangular_MF(a=0, b=0, c=0.2), term="N")
        V_2 = FuzzySet(function=Triangular_MF(a=0, b=0.2, c=0.4), term="MB")
        V_3 = FuzzySet(function=Triangular_MF(a=0.2, b=0.4, c=0.6), term="B")
        V_4 = FuzzySet(function=Triangular_MF(a=0.4, b=0.6, c=0.8), term="M")
        V_5 = FuzzySet(function=Triangular_MF(a=0.6, b=0.8, c=1.0), term="A")
        V_6 = FuzzySet(function=Triangular_MF(a=0.8, b=1.0, c=1.2), term="MA")
        V_7 = FuzzySet(function=Triangular_MF(a=1.0, b=1.2, c=1.4), term="EA")
        V_8 = FuzzySet(function=Triangular_MF(a=1.2, b=1.4, c=1.4), term="L")
        LV5 = LinguisticVariable([V_1, V_2, V_3, V_4, V_5, V_6, V_7, V_8], concept="Voltaje de Control", universe_of_discourse=[0,1.4])
        FS.add_linguistic_variable("V", LV5)

        RULES = []
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS N) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS M)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS N) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB)) THEN (V IS A)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS N) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS N) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS N) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS N)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS N) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS B)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS N) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MB)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MB) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS M)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MB) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB)) THEN (V IS A)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MB) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MB) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS M)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MB) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS B)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MB) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS N)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MB) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS B)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS B) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS A)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS B) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS B) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS A)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS B) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS B) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS B) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS B)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS M) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS A)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS M) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS M) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS M) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS A)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS M) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS M) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS A) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS A)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS A) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS A) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA) OR (CET IS N)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS A) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS A)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS A) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS A) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MA) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA) OR (CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MA) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA) OR (CET IS N)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MA) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MA) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF ((RPM IS N) OR (RPM IS B)) AND (T IS MA) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")

        RULES.append("IF (RPM IS M) AND (T IS N) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS M) AND (T IS N) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB)) THEN (V IS MA)")
        RULES.append("IF (RPM IS M) AND (T IS N) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS M) AND (T IS N) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF (RPM IS M) AND (T IS N) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS N)")
        RULES.append("IF (RPM IS M) AND (T IS N) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS B)")
        RULES.append("IF (RPM IS M) AND (T IS N) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MB)")
        RULES.append("IF (RPM IS M) AND (T IS MB) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS M) AND (T IS MB) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB)) THEN (V IS MA)")
        RULES.append("IF (RPM IS M) AND (T IS MB) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS M) AND (T IS MB) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS M)")
        RULES.append("IF (RPM IS M) AND (T IS MB) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS B)")
        RULES.append("IF (RPM IS M) AND (T IS MB) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS N)")
        RULES.append("IF (RPM IS M) AND (T IS MB) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS B)")
        RULES.append("IF (RPM IS M) AND (T IS B) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MA)")
        RULES.append("IF (RPM IS M) AND (T IS B) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS M) AND (T IS B) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS M) AND (T IS B) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")
        RULES.append("IF (RPM IS M) AND (T IS B) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF (RPM IS M) AND (T IS B) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS B)")
        RULES.append("IF (RPM IS M) AND (T IS M) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MA)")
        RULES.append("IF (RPM IS M) AND (T IS M) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS M) AND (T IS M) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MA)")
        RULES.append("IF (RPM IS M) AND (T IS M) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS M) AND (T IS M) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF (RPM IS M) AND (T IS M) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")
        RULES.append("IF (RPM IS M) AND (T IS A) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MA)")
        RULES.append("IF (RPM IS M) AND (T IS A) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS M) AND (T IS A) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS M) AND (T IS A) AND ((ET IS NN) OR (ET IS PN)) AND (CET IS N) THEN (V IS MA)")
        RULES.append("IF (RPM IS M) AND (T IS A) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS M) AND (T IS A) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF (RPM IS M) AND (T IS A) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")
        RULES.append("IF (RPM IS M) AND (T IS MA) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA) OR (CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS M) AND (T IS MA) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA) OR (CET IS N)) THEN (V IS EA)")
        RULES.append("IF (RPM IS M) AND (T IS MA) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF (RPM IS M) AND (T IS MA) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF (RPM IS M) AND (T IS MA) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")

        RULES.append("IF (RPM IS A) AND (T IS N) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS A) AND (T IS N) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB)) THEN (V IS MA)")
        RULES.append("IF (RPM IS A) AND (T IS N) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS A) AND (T IS N) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF (RPM IS A) AND (T IS N) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS N)")
        RULES.append("IF (RPM IS A) AND (T IS N) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS B)")
        RULES.append("IF (RPM IS A) AND (T IS N) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MB)")
        RULES.append("IF (RPM IS A) AND (T IS MB) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MA)")
        RULES.append("IF (RPM IS A) AND (T IS MB) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB)) THEN (V IS EA)")
        RULES.append("IF (RPM IS A) AND (T IS MB) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS L)")
        RULES.append("IF (RPM IS A) AND (T IS MB) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS A) AND (T IS MB) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")
        RULES.append("IF (RPM IS A) AND (T IS MB) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MB)")
        RULES.append("IF (RPM IS A) AND (T IS MB) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")
        RULES.append("IF (RPM IS A) AND (T IS B) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS A) AND (T IS B) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS L)")
        RULES.append("IF (RPM IS A) AND (T IS B) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS MA)")
        RULES.append("IF (RPM IS A) AND (T IS B) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS A) AND (T IS B) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS B)")
        RULES.append("IF (RPM IS A) AND (T IS B) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS M)")
        RULES.append("IF (RPM IS A) AND (T IS M) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS A) AND (T IS M) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS L)")
        RULES.append("IF (RPM IS A) AND (T IS M) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS A) AND (T IS M) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF (RPM IS A) AND (T IS M) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS B)")
        RULES.append("IF (RPM IS A) AND (T IS M) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS A) AND (T IS A) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS A) AND (T IS A) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS L)")
        RULES.append("IF (RPM IS A) AND (T IS A) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS L)")
        RULES.append("IF (RPM IS A) AND (T IS A) AND ((ET IS NN) OR (ET IS PN)) AND (CET IS N) THEN (V IS EA)")
        RULES.append("IF (RPM IS A) AND (T IS A) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS MA)")
        RULES.append("IF (RPM IS A) AND (T IS A) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS B)")
        RULES.append("IF (RPM IS A) AND (T IS A) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS A)")
        RULES.append("IF (RPM IS A) AND (T IS MA) AND ((ET IS NMB) OR (ET IS NB) OR (ET IS NM) OR (ET IS NA) OR (ET IS NMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA) OR (CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS L)")
        RULES.append("IF (RPM IS A) AND (T IS MA) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA) OR (CET IS N)) THEN (V IS L)")
        RULES.append("IF (RPM IS A) AND (T IS MA) AND ((ET IS NN) OR (ET IS PN)) AND ((CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS EA)")
        RULES.append("IF (RPM IS A) AND (T IS MA) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS NMB) OR (CET IS NB) OR (CET IS NM) OR (CET IS NA) OR (CET IS NMA)) THEN (V IS B)")
        RULES.append("IF (RPM IS A) AND (T IS MA) AND ((ET IS PMB) OR (ET IS PB) OR (ET IS PM) OR (ET IS PA) OR (ET IS PMA)) AND ((CET IS N) OR (CET IS PMB) OR (CET IS PB) OR (CET IS PM) OR (CET IS PA) OR (CET IS PMA)) THEN (V IS A)")

        FS.add_rules(RULES)
        return FS