# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Usuario\Downloads\read_PWM_py\provisional_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 259)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Aplicar = QtWidgets.QPushButton(self.centralwidget)
        self.Aplicar.setGeometry(QtCore.QRect(180, 180, 61, 31))
        self.Aplicar.setObjectName("Aplicar")
<<<<<<< HEAD
        self.InputVoltage = QtWidgets.QLineEdit(self.centralwidget)
        self.InputVoltage.setGeometry(QtCore.QRect(40, 190, 113, 20))
        self.InputVoltage.setObjectName("InputVoltage")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 191, 131))
        self.groupBox.setObjectName("groupBox")
        self.Ch2 = QtWidgets.QLabel(self.groupBox)
        self.Ch2.setGeometry(QtCore.QRect(130, 50, 60, 13))
=======
        self.Ch1 = QtWidgets.QLabel(self.centralwidget)
        self.Ch1.setGeometry(QtCore.QRect(80, 50, 47, 13))
        self.Ch1.setObjectName("Ch1")
        self.Ch2 = QtWidgets.QLabel(self.centralwidget)
        self.Ch2.setGeometry(QtCore.QRect(80, 70, 47, 13))
>>>>>>> 1647d561ef571c11ccc42be3ababb6c635157c87
        self.Ch2.setObjectName("Ch2")
        self.Ch4_2 = QtWidgets.QLabel(self.groupBox)
        self.Ch4_2.setGeometry(QtCore.QRect(30, 90, 100, 13))
        self.Ch4_2.setObjectName("Ch4_2")
        self.Ch2_2 = QtWidgets.QLabel(self.groupBox)
        self.Ch2_2.setGeometry(QtCore.QRect(30, 50, 100, 13))
        self.Ch2_2.setObjectName("Ch2_2")
        self.Ch1 = QtWidgets.QLabel(self.groupBox)
        self.Ch1.setGeometry(QtCore.QRect(130, 30, 60, 13))
        self.Ch1.setObjectName("Ch1")
        self.Ch1_2 = QtWidgets.QLabel(self.groupBox)
        self.Ch1_2.setGeometry(QtCore.QRect(30, 30, 90, 13))
        self.Ch1_2.setObjectName("Ch1_2")
        self.Ch3_2 = QtWidgets.QLabel(self.groupBox)
        self.Ch3_2.setGeometry(QtCore.QRect(30, 70, 47, 13))
        self.Ch3_2.setObjectName("Ch3_2")
        self.Ch3 = QtWidgets.QLabel(self.groupBox)
        self.Ch3.setGeometry(QtCore.QRect(130, 70, 60, 13))
        self.Ch3.setObjectName("Ch3")
        self.Ch4 = QtWidgets.QLabel(self.groupBox)
        self.Ch4.setGeometry(QtCore.QRect(130, 90, 60, 13))
        self.Ch4.setObjectName("Ch4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 20, 191, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Frecuency = QtWidgets.QLabel(self.groupBox_2)
        self.Frecuency.setGeometry(QtCore.QRect(90, 30, 61, 16))
        self.Frecuency.setObjectName("Frecuency")
        self.Frecuency_2 = QtWidgets.QLabel(self.groupBox_2)
        self.Frecuency_2.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.Frecuency_2.setObjectName("Frecuency_2")
<<<<<<< HEAD
        self.Velocidad = QtWidgets.QLabel(self.groupBox_2)
        self.Velocidad.setGeometry(QtCore.QRect(20, 50, 51, 31))
        self.Velocidad.setObjectName("Velocidad")
        self.Velocida_value = QtWidgets.QLabel(self.groupBox_2)
        self.Velocida_value.setGeometry(QtCore.QRect(90, 50, 61, 16))
        self.Velocida_value.setObjectName("Velocida_value")
        self.RPM = QtWidgets.QLabel(self.groupBox_2)
        self.RPM.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.RPM.setObjectName("RPM")
        self.RPM_value = QtWidgets.QLabel(self.groupBox_2)
        self.RPM_value.setGeometry(QtCore.QRect(90, 90, 47, 13))
        self.RPM_value.setObjectName("RPM_value")
        self.groupBox.raise_()
        self.Aplicar.raise_()
        self.InputVoltage.raise_()
        self.groupBox_2.raise_()
=======
        self.InputVoltage = QtWidgets.QLineEdit(self.centralwidget)
        self.InputVoltage.setGeometry(QtCore.QRect(40, 160, 113, 20))
        self.InputVoltage.setObjectName("InputVoltage")
>>>>>>> 1647d561ef571c11ccc42be3ababb6c635157c87
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Aplicar.setText(_translate("MainWindow", "Aplicar\n"
"Voltaje"))
        self.groupBox.setTitle(_translate("MainWindow", "Lectura de voltaje "))
        self.Ch2.setText(_translate("MainWindow", "0V"))
        self.Ch4_2.setText(_translate("MainWindow", "Excitación sensores:"))
        self.Ch2_2.setText(_translate("MainWindow", "Celda de carga 02:"))
        self.Ch1.setText(_translate("MainWindow", "0V"))
        self.Ch1_2.setText(_translate("MainWindow", "Celda de carga 01:"))
        self.Ch3_2.setText(_translate("MainWindow", "PAU:"))
        self.Ch3.setText(_translate("MainWindow", "0V"))
        self.Ch4.setText(_translate("MainWindow", "0V"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Lectura de motor"))
        self.Frecuency.setText(_translate("MainWindow", "0Hz"))
        self.Frecuency_2.setText(_translate("MainWindow", "Frecuencia:"))
        self.Velocidad.setText(_translate("MainWindow", "Velocidad\n"
"lineal:"))
        self.Velocida_value.setText(_translate("MainWindow", "0 Km/h"))
        self.RPM.setText(_translate("MainWindow", "RPM:"))
        self.RPM_value.setText(_translate("MainWindow", "0RPM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
