# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'provisional_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 229)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Aplicar = QtWidgets.QPushButton(self.centralwidget)
        self.Aplicar.setGeometry(QtCore.QRect(180, 150, 61, 31))
        self.Aplicar.setObjectName("Aplicar")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 150, 121, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Ch1 = QtWidgets.QLabel(self.centralwidget)
        self.Ch1.setGeometry(QtCore.QRect(80, 50, 47, 13))
        self.Ch1.setObjectName("Ch1")
        self.Ch2 = QtWidgets.QLabel(self.centralwidget)
        self.Ch2.setGeometry(QtCore.QRect(80, 70, 47, 13))
        self.Ch2.setObjectName("Ch2")
        self.Ch3 = QtWidgets.QLabel(self.centralwidget)
        self.Ch3.setGeometry(QtCore.QRect(80, 90, 47, 13))
        self.Ch3.setObjectName("Ch3")
        self.Ch4 = QtWidgets.QLabel(self.centralwidget)
        self.Ch4.setGeometry(QtCore.QRect(80, 110, 47, 13))
        self.Ch4.setObjectName("Ch4")
        self.Frecuency = QtWidgets.QLabel(self.centralwidget)
        self.Frecuency.setGeometry(QtCore.QRect(330, 110, 61, 16))
        self.Frecuency.setObjectName("Frecuency")
        self.Ch1_2 = QtWidgets.QLabel(self.centralwidget)
        self.Ch1_2.setGeometry(QtCore.QRect(40, 50, 47, 13))
        self.Ch1_2.setObjectName("Ch1_2")
        self.Ch2_2 = QtWidgets.QLabel(self.centralwidget)
        self.Ch2_2.setGeometry(QtCore.QRect(40, 70, 47, 13))
        self.Ch2_2.setObjectName("Ch2_2")
        self.Ch3_2 = QtWidgets.QLabel(self.centralwidget)
        self.Ch3_2.setGeometry(QtCore.QRect(40, 90, 47, 13))
        self.Ch3_2.setObjectName("Ch3_2")
        self.Ch4_2 = QtWidgets.QLabel(self.centralwidget)
        self.Ch4_2.setGeometry(QtCore.QRect(40, 110, 47, 13))
        self.Ch4_2.setObjectName("Ch4_2")
        self.Frecuency_2 = QtWidgets.QLabel(self.centralwidget)
        self.Frecuency_2.setGeometry(QtCore.QRect(260, 110, 61, 16))
        self.Frecuency_2.setObjectName("Frecuency_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Aplicar.setText(_translate("MainWindow", "Aplicar\n"
"Voltaje"))
        self.Ch1.setText(_translate("MainWindow", "0V"))
        self.Ch2.setText(_translate("MainWindow", "0V"))
        self.Ch3.setText(_translate("MainWindow", "0V"))
        self.Ch4.setText(_translate("MainWindow", "0V"))
        self.Frecuency.setText(_translate("MainWindow", "0Hz"))
        self.Ch1_2.setText(_translate("MainWindow", "Ch1:"))
        self.Ch2_2.setText(_translate("MainWindow", "Ch2:"))
        self.Ch3_2.setText(_translate("MainWindow", "Ch3:"))
        self.Ch4_2.setText(_translate("MainWindow", "Ch4:"))
        self.Frecuency_2.setText(_translate("MainWindow", "Frecuencia:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
